import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="p-5 bg-blue-500 shadow-lg shadow-gray-400">
          <Link className="font-semibold" href={"/"}>
            Mon Blog
          </Link>
        </header>
        <main>{children}</main>
        <footer className="p-5 bg-blue-500 ">
          <p className="font-semibold ">TP1 NEXT-JS</p>
        </footer>
      </body>
    </html>
  );
}
